#!/bin/bash
#PBS -wd
#PBS -q normal
#PBS -l ncpus=1
#PBS -l walltime=00:10:00
#PBS -l vmem=6GB
PYTHONPATH=$PYTHONPATH:/short/w84/Shapely/lib/python2.6/site-packages/:.:$HOME/eqrm/trunk/:
export PYTHONPATH

module load python/2.6
module load python/2.6-matplotlib
module load intel-mkl/10.1.3.027

mpirun python setdata_ProbHaz_nat_NCI_save.py
