#!/usr/bin/env python

"""A program to plot memprof output.

Usage: plot_memprof <memprof.out> ...
"""

import sys

from pylab import *

KB = 1024
MB = 1024 * KB
GB = 1024 * MB

def main(files):
    """Plot a memprof.out file.

    files  list of paths to files full of memprof data
    """

    legends = []
    data = []

    for file in files:
        f = open(file)
        lines = f.readlines()
        f.close()

        label = lines[0]
        lines = lines[1:]
        legends.append(label)

        memsize = []
        for line in lines:
            line = line.strip()
            val = int(line) * KB    # value is # 1K blocks
            val = float(val) / GB
            memsize.append(val)

        t = xrange(len(memsize))

        data.append(t)
        data.append(memsize)

    #plot(t, memsize, linewidth=1.0)
    plot(*data)
    plt.legend(legends, 'upper left', shadow=False)

    xlabel('time (s)')
    ylabel('Memory Used (GiB)')
    title('Memory usage by time')
    grid(True)
    show()

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(10)

    main(sys.argv[1:])
