

% workshops
mapping = {'W1','W2','S1L','S1M','S1H','S2L','S2M','S2H','S3','S4L',...
   'S4M','S4H','S5L','S5M','S5H','C1L','C1M','C1H','C2L','C2M',...
    'C2H','C3L','C3M','C3H','PC1','PC2L','PC2M','PC2H','RM1L','RM1M',...
    'RM2L','RM2M','RM2H','URML','URMM','MH','W1MEAN','W1BVTILE',...
    'W1BVMETAL','W1TIMBERTILE','W1TIMBERMETAL','C1LMEAN','C1LSOFT',...
    'C1LNOSOFT','C1MMEAN','C1MSOFT','C1MNOSOFT','C1HMEAN','C1HSOFT',...
    'C1HNOSOFT', 'URMLMEAN', 'URMLTILE','URMLMETAL','URMMMEAN',...
    'URMMTILE','URMMMETAL','BRIDGE1','BRIDGE2','BRIDGE3','BRIDGE4',...
    'BRIDGE5','BRIDGE6','BRIDGE7','BRIDGE8','BRIDGE9','BRIDGE10',...
    'BRIDGE11','BRIDGE12','BRIDGE13','BRIDGE14','ASK_TREVOR'};

class_mapping = {'BUILDING','BUILDING','BUILDING','BUILDING','BUILDING',...
   'BUILDING','BUILDING','BUILDING','BUILDING','BUILDING','BUILDING',...
   'BUILDING','BUILDING','BUILDING','BUILDING','BUILDING','BUILDING',...
   'BUILDING','BUILDING','BUILDING','BUILDING','BUILDING','BUILDING',...
   'BUILDING','BUILDING','BUILDING','BUILDING','BUILDING','BUILDING',...
   'BUILDING','BUILDING','BUILDING','BUILDING','BUILDING','BUILDING',...
   'BUILDING','BUILDING','BUILDING','BUILDING','BUILDING','BUILDING',...
   'BUILDING','BUILDING','BUILDING','BUILDING','BUILDING','BUILDING',...
   'BUILDING','BUILDING','BUILDING','BUILDING','BUILDING','BUILDING',...
   'BUILDING','BUILDING','BUILDING','BRIDGE','BRIDGE','BRIDGE','BRIDGE',...
   'BRIDGE','BRIDGE','BRIDGE','BRIDGE','BRIDGE','BRIDGE',...
   'BRIDGE','BRIDGE','BRIDGE','BRIDGE','BUILDING'};

param_filename='Z:\1\cit\natural_hazard_impacts\earthquake\sandpits\prow\eqrm\eqrm_app\resources\data\bfactorsdb.mat';
csv_name='Z:\1\cit\natural_hazard_impacts\earthquake\sandpits\prow\svn\resources\data\building_paramaters_workshop_1';
building_params_to_csv(param_filename,csv_name,mapping,class_mapping)

param_filename='Z:\1\cit\natural_hazard_impacts\earthquake\sandpits\prow\eqrm\eqrm_app\resources\data\bfactorsdb_wshop_update2.mat';
csv_name='Z:\1\cit\natural_hazard_impacts\earthquake\sandpits\prow\svn\resources\data\building_paramaters_workshop_2';
building_params_to_csv(param_filename,csv_name,mapping,class_mapping)

param_filename='Z:\1\cit\natural_hazard_impacts\earthquake\sandpits\prow\eqrm\eqrm_app\resources\data\bfactorsdb_wshop_update3.mat';
csv_name='Z:\1\cit\natural_hazard_impacts\earthquake\sandpits\prow\svn\resources\data\building_paramaters_workshop_3';
building_params_to_csv(param_filename,csv_name,mapping,class_mapping)


param_filename='Z:\1\cit\natural_hazard_impacts\earthquake\sandpits\prow\eqrm\eqrm_app\resources\data\bfactorsdb_hazus.mat';
csv_name='Z:\1\cit\natural_hazard_impacts\earthquake\sandpits\prow\svn\resources\data\building_paramaters_hazus';
building_params_to_csv(param_filename,csv_name,mapping,class_mapping)


param_filename='Z:\1\cit\natural_hazard_impacts\earthquake\sandpits\prow\eqrm\eqrm_app\resources\data\bfactorsdb_wshop.mat';
csv_name='Z:\1\cit\natural_hazard_impacts\earthquake\sandpits\prow\svn\resources\data\building_paramaters_workshop';
building_params_to_csv(param_filename,csv_name,mapping,class_mapping)

