function building_params_to_csv(param_filename,...
    csv_name,mapping,class_mapping)

load(param_filename);
% bring in dparams,drift_sd,nsd_factors,params

damage_extent={'slight','moderate','extreme','complete'};
damage_type={'residential_drift_threshold',...
    'non_residential_drift_threshold','acceleration_threshold'};
% declare what matlab uses as damage bins

fid = fopen(strcat(csv_name,'_metadata.txt'),'wt');
fprintf(fid,'generated by building_params_to_csv.m from: \nmatlab data=');

fprintf(fid,'%s',param_filename);
fprintf(fid,'\npwd=');
fprintf(fid,'%s',pwd);
fprintf(fid,'\ndamage_extent=');
fprintf(fid,damage_extent{1});
for i = 2:length(damage_extent)
    fprintf(fid,',');  
    fprintf(fid,damage_extent{i});
end
fprintf(fid,'\ndamage_type=');
fprintf(fid,damage_type{1});
for i = 2:length(damage_type)
    fprintf(fid,',');  
    fprintf(fid,damage_type{i});
end
fclose(fid);

fid = fopen(strcat(csv_name,'_params.csv'),'wt');

fprintf(fid,'structure_class,structure_classification,design_strength,')
fprintf(fid,'height,natural_elastic_period,');
fprintf(fid,'fraction_in_first_mode,height_to_displacement,');
fprintf(fid,'yield_to_design,ultimate_to_yield,ductility,');
fprintf(fid,'damping_s,damping_m,damping_l,damping_Be') ;
for i=1:length(damage_extent)
    fprintf(fid,',');  
    fprintf(fid,'structural_damage_');
    fprintf(fid,damage_extent{i});
end
fprintf(fid,'\n');
%print the header

for i = 1:length(params) % a bit slow
    fprintf(fid,class_mapping{i});%structure_class
    fprintf(fid,',');
    fprintf(fid,mapping{i});%structure_classification
    fprintf(fid,',');
    fprintf(fid,'%10.8f',params(i,1));%design_strength
    fprintf(fid,',');
    fprintf(fid,'%10.8f',params(i,2));%height
    fprintf(fid,',');
    fprintf(fid,'%10.8f',params(i,3));%natural_elastic_period
    fprintf(fid,',');
    fprintf(fid,'%10.8f',params(i,4));%fraction_in_first_mode
    fprintf(fid,',');
    fprintf(fid,'%10.8f',params(i,5));%height_to_displacement
    fprintf(fid,',');
    fprintf(fid,'%10.8f',params(i,6));%yield_to_design
    fprintf(fid,',');
    fprintf(fid,'%10.8f',params(i,7));%ultimate_to_yield
    fprintf(fid,',');
    fprintf(fid,'%10.8f',params(i,8));%ductility
    fprintf(fid,',');
    fprintf(fid,'%10.8f',dparams(i,1));%damping_s
    fprintf(fid,',');
    fprintf(fid,'%10.8f',dparams(i,2));%damping_m
    fprintf(fid,',');
    fprintf(fid,'%10.8f',dparams(i,3));%damping_l
    fprintf(fid,',');
    fprintf(fid,'%10.8f',dparams(i,4));%damping_Be
    for j=1:length(damage_extent)
        fprintf(fid,',');
        fprintf(fid,'%10.8f',drift_sd(i,j));%structural_damage_ j
    end
    fprintf(fid,'\n');    
end
fclose(fid);

fid = fopen(strcat(csv_name,'_non_structural_damage_params.csv'),'wt');

fprintf(fid,'damage_extent');
for i = 1:length(damage_type)
    fprintf(fid,',');
    fprintf(fid,damage_type{i});
end
fprintf(fid,'\n');

% order = ?? damage_type,damage_extent
for i = 1:length(damage_extent)
    fprintf(fid,damage_extent{i});%damage_type
    for j = 1:length(damage_type)
        fprintf(fid,',');
        fprintf(fid,'%10.8f',nsd_factors(j,i));%slight
    end
    fprintf(fid,'\n');    
end
fclose(fid);
    