#!/bin/bash
#PBS -wd
#PBS -q normal
#PBS -l walltime=2:00:00,vmem=20GB
#PBS -l ncpus=64
#PBS -l jobfs=200GB
PYTHONPATH=$PYTHONPATH:/short/w84/Shapely/lib/python2.6/site-packages/:.:$HOME/eqrm/trunk/:
export PYTHONPATH

module load python/2.6
module load python/2.6-matplotlib
module load intel-mkl/10.1.3.027

mpirun python setdata_ProbHaz_NCI.py
