#!/usr/bin/env python

"""
Auto generate licences.
This has nothing to do with earthquakes.
It is a data bookkeeping script.
  
  Copyright 2007 by Geoscience Australia
"""


import os


from eqrm_code.ANUGA_utilities.system_tools import compute_checksum
from os.path import join, basename, splitext
from os import walk

def write_licence(path_file, author,accountable):

	root, ext = splitext(path_file)
	# Create associated license file
        path_license_filename = root + '.lic'
	file = basename(path_file)
	licfid = open(path_license_filename, 'w')
	xml_string = """<?xml version="1.0" encoding="iso-8859-1"?>

  <ga_license_file>
    <metadata>
      <author>%s</author>
    </metadata>
    <datafile>
      <filename>%s</filename>
      <checksum>%s</checksum>
      <publishable>Yes</publishable>
      <accountable>%s</accountable>
      <source>HAZUS</source>
      <IP_owner>?</IP_owner>
      <IP_info>GNU General Public License</IP_info>
    </datafile>

  </ga_license_file>
""" %(author, file,str(compute_checksum(path_file)) ,accountable)
        
        licfid.write(xml_string)
	licfid.close()
      #<source>Generated by ANUGA development team</source>
        
def add_licences(extension, author,accountable):
    files = os.listdir('.')
    ex_len = len(extension)
    files = [x for x in files if x[-ex_len:] == extension]
    #print "files", files
    for file in files:
        write_licence(file,author,accountable)
   
def add_licences_recursively(root, extension, start_text, author,accountable):
    """
    Add licence files into a directory

    root - the directory to start adding licence files into
    extension - only add licences to files with this extension
    start_text - only add licences to files with this start text
    author - Info added to the licence file
    accountable - Info added to the licence file
    
    """
    for dirpath, filename in identify_datafiles(root,
                                                extension,
                                                start_text,
                                                ['.svn']):

        path_file = join(dirpath, filename)
	print "path_file", path_file
        write_licence(path_file,author, accountable)
     
def identify_datafiles(root,
                       extension_to_use=None,
                       start_text=None,
                       directories_to_ignore=None):
    """ Identify files that might contain data

    """

    for dirpath, dirnames, filenames in walk(root):

	# the caller can modify the dirnames list in-place (perhaps
	# using del or slice assignment), and walk() will only recurse
	# into the subdirectories whose names remain in dirnames; this
	# can be used to prune the search
	
        for ignore in directories_to_ignore:
            if ignore in dirnames:
                dirnames.remove(ignore)  # don't visit ignored directories
	#print "filenames", filenames
        for filename in filenames:
            # Ignore extensions that need no IP checklicence
            #print "filename to check extension", filename
            if filename.endswith(extension_to_use) and \
                   filename.startswith(start_text):
                yield dirpath, filename

#-------------------------------------------------------------
if __name__ == "__main__":
    #write_licence('b_types.csv','Duncan Gray','Duncan Gray')
#     add_licences_recursively('.',
# 			     '.csv','u','Peter Row',
# 			     'Duncan Gray')
    add_licences_recursively('.',
			     '','iot','?',
			     'Duncan Gray')
