#!/bin/bash
#PBS -wd 
#PBS -q express
#PBS -l walltime=0:45:00,vmem=500MB
PYTHONPATH=$PYTHONPATH:/short/w84/Shapely/lib/python2.6/site-packages/:.:/home/547/dsg547/eqrm/trunk/:
export PYTHONPATH

module load python/2.6
module load python/2.6-matplotlib
module load intel-mkl/10.1.3.027

python check_scenarios.py
